"""Updating TechOnboardingServerData table

Revision ID: 06c49f4dc1d0
Revises: ec4da5416452
Create Date: 2026-07-23 08:16:47.774445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '06c49f4dc1d0'
down_revision: Union[str, Sequence[str], None] = 'ec4da5416452'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tech_onboarding_server_data', sa.Column('tech_type', sa.String(length=80), nullable=True))
    op.drop_index(op.f('ix_tech_onboarding_server_data_hostname'), table_name='tech_onboarding_server_data')
    op.create_index(op.f('ix_tech_onboarding_server_data_tech_type'), 'tech_onboarding_server_data', ['tech_type'], unique=False)
    op.drop_column('tech_onboarding_server_data', 'hostname')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tech_onboarding_server_data', sa.Column('hostname', mysql.VARCHAR(length=80), nullable=True))
    op.drop_index(op.f('ix_tech_onboarding_server_data_tech_type'), table_name='tech_onboarding_server_data')
    op.create_index(op.f('ix_tech_onboarding_server_data_hostname'), 'tech_onboarding_server_data', ['hostname'], unique=False)
    op.drop_column('tech_onboarding_server_data', 'tech_type')
    # ### end Alembic commands ###
