"""Updating foreign keys

Revision ID: 1aa2f0a4eb76
Revises: c563d961245c
Create Date: 2026-07-19 14:47:26.699594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aa2f0a4eb76'
down_revision: Union[str, Sequence[str], None] = 'c563d961245c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_data', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'request_data', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'request_data', type_='foreignkey')
    op.drop_column('request_data', 'user_id')
    # ### end Alembic commands ###
