"""Updating RequestData model to contain status

Revision ID: 2a078a2d1efb
Revises: 07db10083f0b
Create Date: 2026-07-23 06:15:40.842285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a078a2d1efb'
down_revision: Union[str, Sequence[str], None] = '07db10083f0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_data', sa.Column('status', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request_data', 'status')
    # ### end Alembic commands ###
