"""Updating relationships

Revision ID: 74a2ff780657
Revises: 6d2800426480
Create Date: 2026-07-14 06:42:16.235684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74a2ff780657'
down_revision: Union[str, Sequence[str], None] = '6d2800426480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_data_ticket_number'), table_name='request_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_request_data_ticket_number'), 'request_data', ['ticket_number'], unique=False)
    # ### end Alembic commands ###
