"""Update RequestData table

Revision ID: 76dea311a8ac
Revises: e73c04c02f15
Create Date: 2026-07-14 06:35:39.515215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76dea311a8ac'
down_revision: Union[str, Sequence[str], None] = 'e73c04c02f15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ci_onboading_server_data_hostname'), table_name='ci_onboarding_server_data')
    op.drop_index(op.f('ix_ci_onboading_server_data_id'), table_name='ci_onboarding_server_data')
    op.drop_index(op.f('ix_ci_onboading_server_data_ip_address'), table_name='ci_onboarding_server_data')
    op.drop_index(op.f('ix_ci_onboading_server_data_serial_number'), table_name='ci_onboarding_server_data')
    op.create_index(op.f('ix_ci_onboarding_server_data_hostname'), 'ci_onboarding_server_data', ['hostname'], unique=False)
    op.create_index(op.f('ix_ci_onboarding_server_data_id'), 'ci_onboarding_server_data', ['id'], unique=False)
    op.create_index(op.f('ix_ci_onboarding_server_data_ip_address'), 'ci_onboarding_server_data', ['ip_address'], unique=False)
    op.create_index(op.f('ix_ci_onboarding_server_data_serial_number'), 'ci_onboarding_server_data', ['serial_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ci_onboarding_server_data_serial_number'), table_name='ci_onboarding_server_data')
    op.drop_index(op.f('ix_ci_onboarding_server_data_ip_address'), table_name='ci_onboarding_server_data')
    op.drop_index(op.f('ix_ci_onboarding_server_data_id'), table_name='ci_onboarding_server_data')
    op.drop_index(op.f('ix_ci_onboarding_server_data_hostname'), table_name='ci_onboarding_server_data')
    op.create_index(op.f('ix_ci_onboading_server_data_serial_number'), 'ci_onboarding_server_data', ['serial_number'], unique=False)
    op.create_index(op.f('ix_ci_onboading_server_data_ip_address'), 'ci_onboarding_server_data', ['ip_address'], unique=False)
    op.create_index(op.f('ix_ci_onboading_server_data_id'), 'ci_onboarding_server_data', ['id'], unique=False)
    op.create_index(op.f('ix_ci_onboading_server_data_hostname'), 'ci_onboarding_server_data', ['hostname'], unique=False)
    # ### end Alembic commands ###
