"""Initial schema

Revision ID: d5bbf70672ec
Revises: 
Create Date: 2026-07-14 06:21:10.964952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5bbf70672ec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_data',
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('ticket_number', sa.String(length=25), nullable=False),
    sa.Column('ticket_type', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('ticket_number')
    )
    op.create_index(op.f('ix_request_data_ticket_id'), 'request_data', ['ticket_id'], unique=True)
    op.create_index(op.f('ix_request_data_ticket_number'), 'request_data', ['ticket_number'], unique=False)
    op.create_table('ci_onboading_server_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=80), nullable=True),
    sa.Column('hostname', sa.String(length=80), nullable=True),
    sa.Column('serial_number', sa.String(length=80), nullable=True),
    sa.Column('operating_system', sa.String(length=80), nullable=True),
    sa.Column('os_version', sa.String(length=80), nullable=True),
    sa.Column('cpu', sa.Integer(), nullable=True),
    sa.Column('memory', sa.Integer(), nullable=True),
    sa.Column('hard_disk', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.String(length=25), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['request_data.ticket_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ci_onboading_server_data_hostname'), 'ci_onboading_server_data', ['hostname'], unique=False)
    op.create_index(op.f('ix_ci_onboading_server_data_id'), 'ci_onboading_server_data', ['id'], unique=False)
    op.create_index(op.f('ix_ci_onboading_server_data_ip_address'), 'ci_onboading_server_data', ['ip_address'], unique=False)
    op.create_index(op.f('ix_ci_onboading_server_data_serial_number'), 'ci_onboading_server_data', ['serial_number'], unique=False)
    op.create_table('tech_onboarding_server_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=80), nullable=True),
    sa.Column('hostname', sa.String(length=80), nullable=True),
    sa.Column('tech_name', sa.String(length=80), nullable=False),
    sa.Column('tech_version', sa.String(length=10), nullable=False),
    sa.Column('request_id', sa.String(length=25), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['request_data.ticket_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tech_onboarding_server_data_hostname'), 'tech_onboarding_server_data', ['hostname'], unique=False)
    op.create_index(op.f('ix_tech_onboarding_server_data_id'), 'tech_onboarding_server_data', ['id'], unique=False)
    op.create_index(op.f('ix_tech_onboarding_server_data_ip_address'), 'tech_onboarding_server_data', ['ip_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tech_onboarding_server_data_ip_address'), table_name='tech_onboarding_server_data')
    op.drop_index(op.f('ix_tech_onboarding_server_data_id'), table_name='tech_onboarding_server_data')
    op.drop_index(op.f('ix_tech_onboarding_server_data_hostname'), table_name='tech_onboarding_server_data')
    op.drop_table('tech_onboarding_server_data')
    op.drop_index(op.f('ix_ci_onboading_server_data_serial_number'), table_name='ci_onboading_server_data')
    op.drop_index(op.f('ix_ci_onboading_server_data_ip_address'), table_name='ci_onboading_server_data')
    op.drop_index(op.f('ix_ci_onboading_server_data_id'), table_name='ci_onboading_server_data')
    op.drop_index(op.f('ix_ci_onboading_server_data_hostname'), table_name='ci_onboading_server_data')
    op.drop_table('ci_onboading_server_data')
    op.drop_index(op.f('ix_request_data_ticket_number'), table_name='request_data')
    op.drop_index(op.f('ix_request_data_ticket_id'), table_name='request_data')
    op.drop_table('request_data')
    # ### end Alembic commands ###
