"""Updating RequestData model to contain status_updated_by

Revision ID: ec4da5416452
Revises: 2a078a2d1efb
Create Date: 2026-07-23 06:32:35.678784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec4da5416452'
down_revision: Union[str, Sequence[str], None] = '2a078a2d1efb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_data', sa.Column('status_updated_by', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request_data', 'status_updated_by')
    # ### end Alembic commands ###
